apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: production
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:25.5.1
        ports:
        - containerPort: 9000
          name: native
        - containerPort: 8123
          name: http
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        env:
        - name: CLICKHOUSE_DB
          value: "default"
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: s3files-sc
      resources:
        requests:
          storage: 500Gi
