apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-s3files-pv
  labels:
    app: clickhouse
    storage: s3files
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3files-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: s3files:fs-REPLACE_WITH_YOUR_FILESYSTEM_ID
    volumeAttributes:
      mounttargetip: "REPLACE_WITH_YOUR_MOUNT_TARGET_IP"
  claimRef:
    namespace: production
    name: data-volume-clickhouse-0
